### ISSUE TITLE
update to python 3.7

### ISSUE THREAD

**Issue by empt1xo** [Fogapod/KiwiBot#3]
```$ bash run.sh
run.sh: line 4: python3.6: command not found
From https://github.com/Fogapod/KiwiBot
 * branch            master     -> FETCH_HEAD
Already up to date.
Restarting in 9 seconds...
``` 
bruh moment #4

**Comment by empt1xo** [comment]
😠

**Comment by Fogapod** [comment]
I don't think bot is tested enough and is ready for 3.7. I see no need for this yet. Would be nice to have python version configurable though.

To fix your issue, edit `run.sh` file manually and use your python version

**Comment by empt1xo** [comment]
ass

**Comment by Fogapod** [comment]
Resoled by https://github.com/Fogapod/KiwiBot/commit/b589059ccc49b9772da37cf500c80a7a02d343a0
